import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,ErrorBox,Field,ObjectEditor,Loading,Modal,PageHeader,Toast,tone}from'../components/UI.jsx';

const CUSTOMER_WEB_BASE=(import.meta.env.VITE_LUKE_SHOP_CUSTOMER_WEB_BASE_URL||'').replace(/\/$/,'');
const storefrontUrl=detail=>`${CUSTOMER_WEB_BASE}${detail?.storefront_path||`/t/${encodeURIComponent(detail?.slug||'')}`}`;
const storePath=(detail,store)=>`/t/${encodeURIComponent(detail.slug)}${store?.is_primary?'':`/s/${encodeURIComponent(store?.slug||'')}`}`;

export function ClientsPage(){
 const{api,isOwner}=useAuth();
 const[rows,setRows]=useState([]),[plans,setPlans]=useState([]),[templates,setTemplates]=useState([]),[q,setQ]=useState(''),[status,setStatus]=useState(''),[err,setErr]=useState(null),[loading,setLoading]=useState(true),[create,setCreate]=useState(false),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[toast,setToast]=useState('');
 const load=async()=>{setLoading(true);setErr(null);try{const[a,b,c]=await Promise.all([api.request('/v1/platform/tenants',{query:{q,status}}),api.request('/v1/platform/plans'),api.request('/v1/platform/templates')]);setRows(a.data.tenants||[]);setPlans(b.data.plans||[]);setTemplates(c.data.templates||[])}catch(e){setErr(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[q,status]);
 const open=async r=>{setSelected(r);setDetail(null);try{const d=await api.request(`/v1/platform/tenants/${encodeURIComponent(r.id)}`);setDetail(d.data.tenant)}catch(e){setErr(e)}};
 return <><PageHeader title="Client platforms" description="Create and manage tenant owners, stores, plans, modules, domains and storefront routes." actions={isOwner&&<button className="primary" onClick={()=>setCreate(true)}>+ Create client platform</button>}/><ErrorBox error={err}/><div className="toolbar"><input placeholder="Search name or slug" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All status</option><option>ACTIVE</option><option>SUSPENDED</option><option>DISABLED</option></select></div><Card title="Tenants" subtitle={`${rows.length} client platform(s)`}>{loading?<Loading/>:<div className="table"><div className="tr head"><span>Client</span><span>Plan</span><span>Stores</span><span>Customers</span><span>Status</span><span/></div>{rows.map(r=><button className="tr" key={r.id} onClick={()=>open(r)}><span><strong>{r.name}</strong><small>{r.slug}</small></span><span>{r.plan_key||'—'}</span><span>{r.stores}</span><span>{r.customers}</span><span><Badge tone={tone(r.status)}>{r.status}</Badge></span><span>Manage →</span></button>)}</div>}</Card><CreateClient open={create} onClose={()=>setCreate(false)} api={api} plans={plans} templates={templates} onDone={()=>{setCreate(false);setToast('Client platform created');load()}}/><ClientDetail open={Boolean(selected)} onClose={()=>{setSelected(null);setDetail(null)}} detail={detail} api={api} plans={plans} templates={templates} isOwner={isOwner} onChanged={async message=>{setToast(message||'Client platform updated');await load();if(selected)open(selected)}}/><Toast message={toast} onDone={()=>setToast('')}/></>;
}

function CreateClient({open,onClose,api,plans,templates,onDone}){
 const[form,setForm]=useState({name:'',slug:'',owner_name:'Owner',owner_email:'',owner_password:'',plan_key:'STARTER',template_key:'MODERN_COMMERCE',currency:'USD',locale:'en',timezone:'UTC'}),[err,setErr]=useState(null),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);setErr(null);try{await api.request('/v1/platform/tenants',{method:'POST',body:form});onDone()}catch(x){setErr(x)}finally{setBusy(false)}};
 return <Modal open={open} onClose={onClose} title="Create client platform" size="lg"><form className="form-grid" onSubmit={submit}><ErrorBox error={err}/><Field label="Client name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Tenant slug"><input required placeholder="abc-fashion" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase()})}/></Field><Field label="Owner name"><input value={form.owner_name} onChange={e=>setForm({...form,owner_name:e.target.value})}/></Field><Field label="Owner email"><input type="email" required value={form.owner_email} onChange={e=>setForm({...form,owner_email:e.target.value})}/></Field><Field label="Temporary owner password" hint="At least 12 characters"><input type="password" minLength="12" required value={form.owner_password} onChange={e=>setForm({...form,owner_password:e.target.value})}/></Field><Field label="Plan"><select value={form.plan_key} onChange={e=>setForm({...form,plan_key:e.target.value})}>{plans.map(p=><option key={p.key}>{p.key}</option>)}</select></Field><Field label="Storefront template"><select value={form.template_key} onChange={e=>setForm({...form,template_key:e.target.value})}>{templates.map(t=><option key={t.key} value={t.key}>{t.name} · {t.key}</option>)}</select></Field><Field label="Currency"><input maxLength="3" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></Field><Field label="Locale"><input value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}/></Field><Field label="Timezone"><input value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field><div className="span2 right"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create tenant + owner'}</button></div></form></Modal>;
}

function ClientDetail({open,onClose,detail,api,plans,templates,isOwner,onChanged}){
 const[tenantName,setTenantName]=useState(''),[plan,setPlan]=useState('STARTER'),[status,setStatus]=useState('ACTIVE'),[currency,setCurrency]=useState('USD'),[locale,setLocale]=useState('en'),[timezone,setTimezone]=useState('UTC'),[notes,setNotes]=useState(''),[modules,setModules]=useState({}),[limits,setLimits]=useState({}),[caps,setCaps]=useState({}),[password,setPassword]=useState(''),[ownerForm,setOwnerForm]=useState({display_name:'',email:'',status:'ACTIVE'}),[ownerBusy,setOwnerBusy]=useState(false),[hostname,setHostname]=useState(''),[domainBusy,setDomainBusy]=useState(false),[verification,setVerification]=useState(null),[storeForm,setStoreForm]=useState({name:'',slug:'',is_primary:false,template_key:'MODERN_COMMERCE'}),[storeEdit,setStoreEdit]=useState(null),[storeBusy,setStoreBusy]=useState(false),[err,setErr]=useState(null),[saveBusy,setSaveBusy]=useState(false);
 useEffect(()=>{if(detail){setTenantName(detail.name||'');setPlan(detail.platform?.plan_key||'STARTER');setStatus(detail.status);setCurrency(detail.settings?.currency||'USD');setLocale(detail.settings?.locale||'en');setTimezone(detail.settings?.timezone||'UTC');setNotes(detail.platform?.notes||'');setModules(detail.platform?.overrides?.modules||{});setLimits(detail.platform?.overrides?.limits||{});setCaps(detail.platform?.overrides?.capabilities||{});setOwnerForm({display_name:detail.owner?.display_name||'',email:detail.owner?.email||'',status:detail.owner?.status||'ACTIVE'});setHostname('');setVerification(null);setStoreForm({name:'',slug:'',is_primary:false,template_key:templates?.[0]?.key||'MODERN_COMMERCE'})}},[detail?.id]);
 if(!open)return null;
 const save=async()=>{setSaveBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}`,{method:'PATCH',body:{name:tenantName.trim(),status,plan_key:plan,currency:currency.trim().toUpperCase(),locale:locale.trim(),timezone:timezone.trim(),notes:notes.trim()||null,modules,limits,capabilities:caps}});await onChanged('Client controls updated')}catch(e){setErr(e)}finally{setSaveBusy(false)}};
 const saveOwner=async()=>{setOwnerBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/owner`,{method:'PATCH',body:{display_name:ownerForm.display_name.trim(),email:ownerForm.email.trim().toLowerCase(),status:ownerForm.status}});await onChanged('Owner account updated')}catch(e){setErr(e)}finally{setOwnerBusy(false)}};
 const reset=async()=>{setOwnerBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/owner/reset-password`,{method:'POST',body:{new_password:password}});setPassword('');await onChanged('Owner password reset')}catch(e){setErr(e)}finally{setOwnerBusy(false)}};
 const logout=async()=>{setOwnerBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/owner/force-logout`,{method:'POST',body:{}});await onChanged('Owner sessions revoked')}catch(e){setErr(e)}finally{setOwnerBusy(false)}};
 const addDomain=async()=>{if(!hostname.trim())return;setDomainBusy(true);setErr(null);try{const result=await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/domains`,{method:'POST',body:{hostname:hostname.trim(),is_primary:(detail.domains||[]).length===0}});setHostname('');setVerification({domainId:result.data.domain.id,hostname:result.data.domain.hostname,...result.data.verification});await onChanged('Domain added. Add the TXT record before checking DNS.')}catch(e){setErr(e)}finally{setDomainBusy(false)}};
 const verifyDomain=async id=>{setDomainBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/domains/${encodeURIComponent(id)}/verify`,{method:'POST',body:{}});if(verification?.domainId===id)setVerification(null);await onChanged('DNS verified and domain activated')}catch(e){setErr(e)}finally{setDomainBusy(false)}};
 const deleteDomain=async id=>{if(!confirm('Remove this storefront domain?'))return;setDomainBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/domains/${encodeURIComponent(id)}`,{method:'DELETE'});if(verification?.domainId===id)setVerification(null);await onChanged('Domain removed')}catch(e){setErr(e)}finally{setDomainBusy(false)}};
 const createStore=async e=>{e.preventDefault();setStoreBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/stores`,{method:'POST',body:{...storeForm,name:storeForm.name.trim(),slug:storeForm.slug.trim().toLowerCase()}});setStoreForm({name:'',slug:'',is_primary:false,template_key:templates?.[0]?.key||'MODERN_COMMERCE'});await onChanged('Store created')}catch(e){setErr(e)}finally{setStoreBusy(false)}};
 const saveStore=async()=>{setStoreBusy(true);setErr(null);try{await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}/stores/${encodeURIComponent(storeEdit.id)}`,{method:'PATCH',body:{name:storeEdit.name.trim(),slug:storeEdit.slug.trim().toLowerCase(),status:storeEdit.status,is_primary:Boolean(storeEdit.is_primary)}});setStoreEdit(null);await onChanged('Store updated')}catch(e){setErr(e)}finally{setStoreBusy(false)}};
 const url=detail?storefrontUrl(detail):'';
 return <Modal open={open} onClose={onClose} title={detail?.name||'Client platform'} size="xl">{!detail?<Loading/>:<><ErrorBox error={err}/><div className="detail-top"><div><span>Slug</span><strong>{detail.slug}</strong></div><div><span>Owner</span><strong>{detail.owner?.email||'—'}</strong></div><div><span>Stores</span><strong>{detail.stores?.total||0}</strong></div><div><span>Status</span><Badge tone={tone(detail.status)}>{detail.status}</Badge></div></div><div className="grid2">
  <Card title="Customer storefront" subtitle="Published route for the tenant primary store"><div className="form-stack"><Field label="Published storefront URL"><input readOnly value={url}/></Field><div className="button-row"><button className="primary" onClick={()=>window.open(url,'_blank','noopener,noreferrer')}>Open storefront</button><button className="secondary" onClick={()=>navigator.clipboard?.writeText(url)}>Copy URL</button></div><p className="muted">Primary route: {detail.storefront_path}. Additional stores use /s/&#123;storeSlug&#125;.</p></div></Card>
  <Card title="Client identity & lifecycle"><div className="form-stack"><Field label="Client name"><input disabled={!isOwner} value={tenantName} onChange={e=>setTenantName(e.target.value)}/></Field><Field label="Status"><select disabled={!isOwner} value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>SUSPENDED</option><option>DISABLED</option></select></Field><Field label="Plan"><select disabled={!isOwner} value={plan} onChange={e=>setPlan(e.target.value)}>{plans.map(p=><option key={p.key}>{p.key}</option>)}</select></Field><p className="muted">Effective plan: {detail.platform?.plan_name||'—'}. Overrides below merge on top of plan defaults.</p></div></Card>
  <Card title="Regional & internal settings" subtitle="Platform-level tenant configuration"><div className="form-stack"><div className="form-grid"><Field label="Currency"><input disabled={!isOwner} maxLength="3" value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></Field><Field label="Locale"><input disabled={!isOwner} value={locale} onChange={e=>setLocale(e.target.value)}/></Field><Field label="Timezone"><input disabled={!isOwner} value={timezone} onChange={e=>setTimezone(e.target.value)}/></Field></div><Field label="Platform notes" hint="Internal notes for platform operators. Not shown to the merchant or customers."><textarea disabled={!isOwner} maxLength="2000" rows="4" value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div></Card>
  <Card title="Customer identity & login" subtitle="Read-only visibility. The tenant merchant controls these customer-facing settings in Merchant Admin."><div className="identity-governance-card"><div><span>Customer ID prefix</span><strong>{detail.customer_identity?.id_prefix||'CUS'}</strong></div><div><span>Next customer code</span><strong className="mono">{`${detail.customer_identity?.id_prefix||'CUS'}${String(detail.customer_identity?.next_sequence||1).padStart(7,'0')}`}</strong></div><div className="span2"><span>Configured login methods</span><div className="identity-method-chips">{Object.entries(detail.customer_identity?.auth_config||{}).filter(([key,value])=>['email_password','google','telegram','phone'].includes(key)&&Boolean(value)).map(([key])=><b key={key}>{key==='email_password'?'Email & password':key==='google'?'Google':key==='telegram'?'Telegram':'Phone OTP'}</b>)}{!Object.entries(detail.customer_identity?.auth_config||{}).some(([key,value])=>['email_password','google','telegram','phone'].includes(key)&&Boolean(value))&&<em>None enabled</em>}</div></div><p className="span2 muted">Existing customer codes remain immutable if the merchant changes the prefix. Platform operators can inspect configuration here without silently changing a client&apos;s login policy.</p></div></Card>
  <Card title="Owner account" subtitle="Manage the tenant owner identity, access state and sessions"><div className="form-stack"><Field label="Owner display name"><input disabled={!isOwner} value={ownerForm.display_name} onChange={e=>setOwnerForm({...ownerForm,display_name:e.target.value})}/></Field><Field label="Owner email"><input disabled={!isOwner} type="email" value={ownerForm.email} onChange={e=>setOwnerForm({...ownerForm,email:e.target.value})}/></Field><Field label="Owner status"><select disabled={!isOwner} value={ownerForm.status} onChange={e=>setOwnerForm({...ownerForm,status:e.target.value})}><option>ACTIVE</option><option>SUSPENDED</option><option>BLOCKED</option></select></Field><button className="secondary" disabled={!isOwner||ownerBusy||!ownerForm.display_name.trim()||!ownerForm.email.trim()} onClick={saveOwner}>{ownerBusy?'Working…':'Save owner account'}</button><Field label="Reset owner password" hint="At least 12 characters"><input type="password" minLength="12" value={password} onChange={e=>setPassword(e.target.value)} placeholder="New temporary password"/></Field><div className="button-row"><button className="secondary" disabled={!isOwner||ownerBusy||password.length<12} onClick={reset}>Reset password</button><button className="danger" disabled={!isOwner||ownerBusy} onClick={logout}>Force logout</button></div></div></Card>
  <Card title="Custom domains" subtitle="Luke verifies a DNS TXT challenge before a domain becomes active"><div className="form-stack"><div className="button-row"><input placeholder="shop.clientdomain.com" value={hostname} onChange={e=>setHostname(e.target.value.toLowerCase())}/><button className="secondary" disabled={!isOwner||domainBusy||!hostname.trim()} onClick={addDomain}>Add domain</button></div>{verification&&<div className="dns-verification-box"><strong>DNS verification required</strong><p>Add this TXT record at your DNS provider. The verification value is shown only immediately after the domain is created.</p><Field label="TXT name"><div className="copy-field"><input readOnly value={verification.name}/><button className="secondary" onClick={()=>navigator.clipboard?.writeText(verification.name)}>Copy</button></div></Field><Field label="TXT value"><div className="copy-field"><input readOnly value={verification.value}/><button className="secondary" onClick={()=>navigator.clipboard?.writeText(verification.value)}>Copy</button></div></Field><button className="primary" disabled={domainBusy} onClick={()=>verifyDomain(verification.domainId)}>Check DNS now</button></div>}{(detail.domains||[]).length?<div className="history-list">{detail.domains.map(d=><div key={d.id}><div><strong>{d.hostname}</strong><span>{d.status}{d.is_primary?' · primary':''}{d.store_slug?` · ${d.store_slug}`:''}</span></div><div className="button-row">{d.status==='PENDING'&&isOwner&&<button className="secondary" disabled={domainBusy} onClick={()=>verifyDomain(d.id)}>Check DNS</button>}{isOwner&&<button className="danger-mini" disabled={domainBusy} onClick={()=>deleteDomain(d.id)}>×</button>}</div></div>)}</div>:<p className="muted">No custom domains yet.</p>}</div></Card>
 </div>
 <Card title="Tenant stores" subtitle="Create and control every storefront under this tenant"><div className="store-control-grid"><div>{(detail.store_list||[]).length?<div className="store-admin-list">{detail.store_list.map(s=><div className="store-admin-row" key={s.id}><div><strong>{s.name}</strong><span>/{s.slug} · {s.status}{s.is_primary?' · primary':''}</span></div><div className="button-row"><button className="secondary" onClick={()=>window.open(`${CUSTOMER_WEB_BASE}${storePath(detail,s)}`,'_blank','noopener,noreferrer')}>Open</button>{isOwner&&<button className="secondary" onClick={()=>setStoreEdit({...s})}>Edit</button>}</div></div>)}</div>:<p className="muted">No stores found.</p>}</div>{isOwner&&<form className="form-stack store-create-form" onSubmit={createStore}><h3>Create store</h3><Field label="Store name"><input required value={storeForm.name} onChange={e=>setStoreForm({...storeForm,name:e.target.value})}/></Field><Field label="Store slug"><input required value={storeForm.slug} onChange={e=>setStoreForm({...storeForm,slug:e.target.value.toLowerCase()})}/></Field><Field label="Starting template"><select value={storeForm.template_key} onChange={e=>setStoreForm({...storeForm,template_key:e.target.value})}>{templates.map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select></Field><label className="inline-check"><input type="checkbox" checked={storeForm.is_primary} onChange={e=>setStoreForm({...storeForm,is_primary:e.target.checked})}/> Make primary store</label><button className="primary" disabled={storeBusy}>{storeBusy?'Creating…':'Create store'}</button></form>}</div></Card>
 <div className="grid3"><ObjectEditor label="Module overrides" value={modules} onChange={setModules}/><ObjectEditor label="Tenant limit overrides" value={limits} onChange={setLimits}/><ObjectEditor label="Capability overrides" value={caps} onChange={setCaps}/></div>{isOwner&&<div className="right"><button className="primary" disabled={saveBusy||!tenantName.trim()||currency.trim().length!==3||!locale.trim()||!timezone.trim()} onClick={save}>{saveBusy?'Saving…':'Save client controls'}</button></div>}
 {storeEdit&&<Modal open={true} onClose={()=>setStoreEdit(null)} title={`Edit ${storeEdit.name}`} footer={<><button className="secondary" onClick={()=>setStoreEdit(null)}>Cancel</button><button className="primary" disabled={storeBusy} onClick={saveStore}>Save store</button></>}><div className="form-stack"><Field label="Store name"><input value={storeEdit.name} onChange={e=>setStoreEdit({...storeEdit,name:e.target.value})}/></Field><Field label="Store slug"><input value={storeEdit.slug} onChange={e=>setStoreEdit({...storeEdit,slug:e.target.value.toLowerCase()})}/></Field><Field label="Status"><select value={storeEdit.status} onChange={e=>setStoreEdit({...storeEdit,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></Field><label className="inline-check"><input type="checkbox" checked={Boolean(storeEdit.is_primary)} onChange={e=>setStoreEdit({...storeEdit,is_primary:e.target.checked})}/> Primary store</label></div></Modal>}
 </>}</Modal>;
}
