import React,{useEffect,useMemo,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,ErrorBox,Loading,Modal,PageHeader,Tabs,Toast,tone}from'../components/UI.jsx';
import{ThemePhosphorIcon}from'../components/ThemePhosphorIcon.jsx';

const SCOPES=['NAVIGATION','TOPIC','CATEGORY','ACCOUNT','ACTION'];
const SCOPE_LABELS={NAVIGATION:'Navigation',TOPIC:'Topic',CATEGORY:'Category',ACCOUNT:'Account',ACTION:'Action'};
const STATUS_TABS=[{value:'all',label:'All'},{value:'published',label:'Published'},{value:'draft',label:'Draft'},{value:'retired',label:'Retired'}];
const API_BASE=String(import.meta.env.VITE_LUKE_SHOP_API_BASE_URL||'').replace(/\/$/,'');
const MAX_IMAGE_BYTES=262144;
const ALLOWED_MIME=new Set(['image/png','image/webp']);
const blankForm=()=>({key:'',name:'',category:'',tags:'',usage_scopes:['TOPIC'],image:null,light_image:null,dark_image:null});
const assetSrc=(row,variant='default')=>row?.asset_path?`${API_BASE}${row.asset_path}${variant==='default'?'':`?variant=${variant}`}`:'';

function readArtwork(file){
 if(!file)return Promise.resolve(null);
 if(!ALLOWED_MIME.has(file.type))return Promise.reject(new Error('Custom icons must be PNG or WebP. SVG is not accepted.'));
 if(file.size<1||file.size>MAX_IMAGE_BYTES)return Promise.reject(new Error('Each icon image must be 256 KB or smaller.'));
 return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Unable to read image file.'));reader.onload=()=>{const data=String(reader.result||''),comma=data.indexOf(',');if(comma<0)return reject(new Error('Unable to encode image file.'));resolve({mime_type:file.type,data_base64:data.slice(comma+1),preview:data,file_name:file.name,byte_size:file.size})};reader.readAsDataURL(file)});
}

export function IconLibraryPage(){
 const{api,isOwner}=useAuth();
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[status,setStatus]=useState('all'),[scope,setScope]=useState('all'),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[toast,setToast]=useState('');
 const[createOpen,setCreateOpen]=useState(false),[form,setForm]=useState(blankForm()),[formError,setFormError]=useState('');
 const load=async()=>{setLoading(true);setError(null);try{const d=await api.request('/v1/platform/icons');setRows(d.data.icons||[])}catch(e){setError(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>rows.filter(row=>{
   if(status!=='all'&&row.status!==status.toUpperCase())return false;
   if(scope!=='all'&&!row.usage_scopes?.includes(scope))return false;
   const q=query.trim().toLowerCase();if(q&&!`${row.name} ${row.key} ${row.category||''} ${row.source_type||''} ${(row.tags||[]).join(' ')}`.toLowerCase().includes(q))return false;
   return true;
 }),[rows,status,scope,query]);
 const counts={all:rows.length,published:rows.filter(x=>x.status==='PUBLISHED').length,draft:rows.filter(x=>x.status==='DRAFT').length,retired:rows.filter(x=>x.status==='RETIRED').length};
 const setScopes=async(row,next)=>{if(!isOwner||row.status==='RETIRED'||next.length===0)return;setBusy(`${row.key}:scopes`);setError(null);try{await api.request(`/v1/platform/icons/${encodeURIComponent(row.key)}/scopes`,{method:'PUT',body:{usage_scopes:next}});setToast(`${row.name} usage updated`);await load()}catch(e){setError(e)}finally{setBusy('')}};
 const lifecycle=async(row,action)=>{setBusy(`${row.key}:${action}`);setError(null);try{if(action==='delete')await api.request(`/v1/platform/icons/${encodeURIComponent(row.key)}`,{method:'DELETE'});else await api.request(`/v1/platform/icons/${encodeURIComponent(row.key)}/${action}`,{method:'POST',body:{}});setToast(action==='publish'?'Icon published':action==='retire'?'Icon retired':'Draft deleted');await load()}catch(e){setError(e)}finally{setBusy('')}};
 const chooseArtwork=async(field,file)=>{setFormError('');try{const value=await readArtwork(file);setForm(old=>({...old,[field]:value}))}catch(e){setFormError(e.message)}};
 const toggleCreateScope=value=>setForm(old=>{const has=old.usage_scopes.includes(value),next=has?old.usage_scopes.filter(x=>x!==value):[...old.usage_scopes,value];return next.length?{...old,usage_scopes:next}:old});
 const createCustom=async()=>{setFormError('');if(!form.image)return setFormError('Default artwork is required.');setBusy('create-custom');try{const body={key:form.key,name:form.name,category:form.category||undefined,usage_scopes:form.usage_scopes,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),image:{mime_type:form.image.mime_type,data_base64:form.image.data_base64}};for(const field of ['light_image','dark_image'])if(form[field])body[field]={mime_type:form[field].mime_type,data_base64:form[field].data_base64};await api.request('/v1/platform/icons/custom-image',{method:'POST',body});setCreateOpen(false);setForm(blankForm());setToast('Custom icon installed as Draft');await load()}catch(e){setFormError(e.message||'Unable to create custom icon.')}finally{setBusy('')}};
 return <><PageHeader eyebrow="Design system governance" title="Platform Icon Library" description="Control the professional icons client admins are allowed to select. Library glyphs and custom multicolor artwork are Platform-owned, explicitly published, and limited to approved usage scopes." actions={isOwner&&<button className="primary" onClick={()=>{setForm(blankForm());setFormError('');setCreateOpen(true)}}>+ Add custom icon</button>}/><ErrorBox error={error}/><div className="icon-library-callout"><div><strong>One approved catalog for every Shope surface</strong><span>Client admins select published icon keys for the requested scope. Custom artwork is stored by the Platform as validated PNG/WebP only; executable SVG, HTML, JavaScript and arbitrary URLs are not accepted.</span></div><div className="icon-library-callout-badges"><Badge tone="success">Phosphor · A1</Badge><Badge tone="success">Custom color artwork · A2</Badge></div></div><Tabs value={status} onChange={setStatus} items={STATUS_TABS.map(x=>({...x,count:counts[x.value]}))}/><div className="icon-library-toolbar"><div className="icon-library-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search icons, categories, keys or tags…"/></div><div className="icon-scope-filter"><button className={scope==='all'?'active':''} onClick={()=>setScope('all')}>All uses</button>{SCOPES.map(s=><button key={s} className={scope===s?'active':''} onClick={()=>setScope(s)}>{SCOPE_LABELS[s]}</button>)}</div></div>{loading?<Loading/>:visible.length===0?<div className="empty"><strong>No matching icons</strong><span>Change the status, scope or search filter.</span></div>:<div className="platform-icon-grid">{visible.map(row=><IconCard key={row.key} row={row} isOwner={isOwner} busy={busy} setScopes={setScopes} lifecycle={lifecycle}/>)}</div>}<CustomIconModal open={createOpen} onClose={()=>setCreateOpen(false)} form={form} setForm={setForm} formError={formError} chooseArtwork={chooseArtwork} toggleScope={toggleCreateScope} createCustom={createCustom} busy={busy}/><Toast message={toast} onDone={()=>setToast('')}/></>;
}

function CustomIconModal({open,onClose,form,setForm,formError,chooseArtwork,toggleScope,createCustom,busy}){
 return <Modal open={open} onClose={onClose} title="Add custom color icon" size="xl" footer={<><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy==='create-custom'} onClick={createCustom}>{busy==='create-custom'?'Creating…':'Create Draft icon'}</button></>}><div className="custom-icon-studio"><section className="custom-icon-form"><label><span>Icon key</span><input value={form.key} onChange={e=>setForm(old=>({...old,key:e.target.value.toUpperCase()}))} placeholder="CUSTOM.VIP_CROWN"/></label><label><span>Name</span><input value={form.name} onChange={e=>setForm(old=>({...old,name:e.target.value}))} placeholder="VIP Crown"/></label><label><span>Category <small>optional</small></span><input value={form.category} maxLength={80} onChange={e=>setForm(old=>({...old,category:e.target.value}))} placeholder="Rewards"/></label><label><span>Tags <small>comma separated</small></span><input value={form.tags} onChange={e=>setForm(old=>({...old,tags:e.target.value}))} placeholder="vip, reward, crown"/></label><fieldset className="custom-icon-scopes"><legend>Allowed client usage</legend><div>{SCOPES.map(scope=><button type="button" key={scope} className={form.usage_scopes.includes(scope)?'selected':''} onClick={()=>toggleScope(scope)}>{SCOPE_LABELS[scope]}</button>)}</div></fieldset><div className="custom-icon-safety"><strong>Safe artwork contract</strong><span>PNG or WebP · 16–512 px · max 256 KB each · static images only. Default artwork is required. Light and Dark variants are optional.</span></div>{formError&&<div className="alert error"><strong>Custom icon</strong><span>{formError}</span></div>}</section><section className="custom-icon-artworks"><ArtworkField label="Default artwork" required value={form.image} onFile={file=>chooseArtwork('image',file)}/><ArtworkField label="Light appearance" value={form.light_image} onFile={file=>chooseArtwork('light_image',file)}/><ArtworkField label="Dark appearance" value={form.dark_image} onFile={file=>chooseArtwork('dark_image',file)}/></section></div></Modal>;
}
function ArtworkField({label,required,value,onFile}){return <label className="custom-artwork-field"><span>{label}{required&&<b>Required</b>}</span><div className="custom-artwork-preview">{value?.preview?<img src={value.preview} alt=""/>:<em>PNG / WebP</em>}</div><input type="file" accept="image/png,image/webp" onChange={e=>onFile(e.target.files?.[0]||null)}/>{value&&<small>{value.file_name} · {Math.ceil(value.byte_size/1024)} KB</small>}</label>}

function IconCard({row,isOwner,busy,setScopes,lifecycle}){
 const scopes=row.usage_scopes||[];const locked=row.status==='RETIRED';const weight=row.color_mode==='DUOTONE'?'duotone':'filled',custom=row.source_type==='CUSTOM_IMAGE';
 const toggle=scope=>{const next=scopes.includes(scope)?scopes.filter(x=>x!==scope):[...scopes,scope];if(next.length)setScopes(row,next)};
 return <section className={`platform-icon-card ${locked?'retired':''} ${custom?'custom-image':''}`}><div className="platform-icon-preview">{custom?<img src={assetSrc(row)} alt=""/>:<ThemePhosphorIcon name={row.library_icon} size={36} active activeStyle={weight}/>}</div><div className="platform-icon-title"><div><strong>{row.name}</strong><code>{row.key}</code></div><Badge tone={tone(row.status)}>{row.status}</Badge></div><div className="platform-icon-meta">{custom?<><span>CUSTOM IMAGE</span><span>{row.asset_mime?.replace('image/','').toUpperCase()}</span><span>{row.asset_width}×{row.asset_height}</span></>:<><span>{row.library_pack}</span><span>{row.color_mode}</span><span>{row.library_icon}</span></>}{row.category&&<span>{row.category}</span>}</div>{custom&&(row.asset_variants?.light||row.asset_variants?.dark)&&<div className="platform-icon-variants"><small>Appearance artwork</small><div><span>Default</span>{row.asset_variants.light&&<span>Light</span>}{row.asset_variants.dark&&<span>Dark</span>}</div></div>}<div className="platform-icon-scopes"><small>Allowed client usage</small><div>{SCOPES.map(scope=><button key={scope} disabled={!isOwner||locked||!!busy} className={scopes.includes(scope)?'selected':''} onClick={()=>toggle(scope)}>{SCOPE_LABELS[scope]}</button>)}</div></div>{(row.tags||[]).length>0&&<div className="platform-icon-tags">{row.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}<div className="platform-icon-foot"><small>{row.status==='PUBLISHED'?'Available to client admins in allowed scopes':row.status==='DRAFT'?'Not listed to client admins until published':'No longer offered for new selections; existing references can keep rendering'}</small>{isOwner&&<div className="button-row">{row.status==='DRAFT'&&<><button className="secondary" disabled={!!busy} onClick={()=>lifecycle(row,'delete')}>Delete</button><button className="primary" disabled={!!busy} onClick={()=>lifecycle(row,'publish')}>Publish</button></>}{row.status==='PUBLISHED'&&<button className="danger" disabled={!!busy} onClick={()=>lifecycle(row,'retire')}>Retire</button>}</div>}</div></section>;
}
