import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,ErrorBox,Field,FriendlyObject,Loading,Modal,PageHeader,Toast,tone}from'../components/UI.jsx';

const blank={key:'',name:'',description:'',status:'ACTIVE',modules:{},limits:{},capabilities:{}};
const clone=x=>JSON.parse(JSON.stringify(x||{}));
const stringify=x=>JSON.stringify(x||{},null,2);
const parse=(value,label)=>{try{const v=JSON.parse(value||'{}');if(!v||Array.isArray(v)||typeof v!=='object')throw new Error();return v}catch{throw new Error(`${label} must be a valid JSON object`)}};

export function PlansPage(){
 const{api,isOwner}=useAuth();const[plans,setPlans]=useState([]),[err,setErr]=useState(null),[edit,setEdit]=useState(null),[creating,setCreating]=useState(false),[toast,setToast]=useState('');
 const load=async()=>{setErr(null);try{const d=await api.request('/v1/platform/plans');setPlans(d.data.plans||[])}catch(e){setErr(e)}};useEffect(()=>{load()},[]);
 const save=async model=>{setErr(null);try{const body={name:model.name.trim(),description:model.description?.trim()||null,status:model.status,modules:parse(model.modulesText,'Modules'),limits:parse(model.limitsText,'Limits'),capabilities:parse(model.capabilitiesText,'Capabilities')};if(model.isNew){await api.request('/v1/platform/plans',{method:'POST',body:{key:model.key.trim().toUpperCase(),...body}});setToast('Plan created')}else{await api.request(`/v1/platform/plans/${encodeURIComponent(model.key)}`,{method:'PATCH',body});setToast('Plan updated')}setEdit(null);setCreating(false);await load()}catch(e){setErr(e)}};
 const openEdit=p=>setEdit({...clone(p),modulesText:stringify(p.modules),limitsText:stringify(p.limits),capabilitiesText:stringify(p.capabilities),isNew:false});
 const openCreate=()=>{const p=clone(blank);setEdit({...p,modulesText:'{}',limitsText:'{}',capabilitiesText:'{}',isNew:true});setCreating(true)};
 return <><PageHeader title="Plans & limits" description="Create and maintain SaaS plans, module defaults, limits and customer-channel capabilities." actions={isOwner&&<button className="primary" onClick={openCreate}>+ Create plan</button>}/><ErrorBox error={err}/>{!plans.length&&!err?<Loading/>:<div className="plan-grid">{plans.map(p=><Card key={p.key} title={p.name} subtitle={p.description}><div className="plan-title-row"><Badge tone={tone(p.status)}>{p.status}</Badge><strong>{p.key}</strong>{isOwner&&<button className="secondary" onClick={()=>openEdit(p)}>Edit plan</button>}</div><h3>Modules</h3><FriendlyObject value={p.modules}/><h3>Limits</h3><FriendlyObject value={p.limits}/><h3>Capabilities</h3><FriendlyObject value={p.capabilities}/></Card>)}</div>}<PlanEditor open={!!edit} model={edit} setModel={setEdit} onClose={()=>{setEdit(null);setCreating(false)}} onSave={save}/><Toast message={toast} onDone={()=>setToast('')}/></>;
}
function PlanEditor({open,model,setModel,onClose,onSave}){if(!model)return null;const patch=(k,v)=>setModel({...model,[k]:v});return <Modal open={open} onClose={onClose} title={model.isNew?'Create plan':`Edit ${model.key}`} size="lg" footer={<><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(model)}>Save plan</button></>}><div className="form-grid"><Field label="Plan key" hint="Stable identifier; cannot be renamed after creation."><input disabled={!model.isNew} value={model.key} onChange={e=>patch('key',e.target.value.toUpperCase())}/></Field><Field label="Name"><input required value={model.name} onChange={e=>patch('name',e.target.value)}/></Field><Field label="Status"><select value={model.status} onChange={e=>patch('status',e.target.value)}><option>ACTIVE</option><option>INACTIVE</option></select></Field><Field label="Description"><textarea value={model.description||''} onChange={e=>patch('description',e.target.value)}/></Field><Field label="Modules JSON" hint="Feature switches inherited by tenants on this plan."><textarea className="json-editor" value={model.modulesText} onChange={e=>patch('modulesText',e.target.value)}/></Field><Field label="Limits JSON" hint="Numeric plan limits such as stores, staff and products."><textarea className="json-editor" value={model.limitsText} onChange={e=>patch('limitsText',e.target.value)}/></Field><Field label="Capabilities JSON" hint="Customer-facing or integration capabilities."><textarea className="json-editor" value={model.capabilitiesText} onChange={e=>patch('capabilitiesText',e.target.value)}/></Field></div></Modal>}
