import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,ErrorBox,Field,Loading,PageHeader,Toast,tone}from'../components/UI.jsx';

const when=value=>value?new Date(value).toLocaleString():'—';

export function ProfilePage(){
 const{api,session,refreshProfile}=useAuth();
 const[profile,setProfile]=useState(session?.user||null),[name,setName]=useState(session?.user?.display_name||''),[sessions,setSessions]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[err,setErr]=useState(null),[toast,setToast]=useState('');
 const[pw,setPw]=useState({current_password:'',new_password:'',confirm:''});
 const load=async()=>{setLoading(true);setErr(null);try{const[me,ss]=await Promise.all([api.request('/v1/platform/me'),api.request('/v1/platform/me/sessions')]);setProfile(me.data.user);setName(me.data.user.display_name||'');setSessions(ss.data.sessions||[])}catch(e){setErr(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const saveProfile=async e=>{e.preventDefault();setBusy('profile');setErr(null);try{const d=await api.request('/v1/platform/me',{method:'PATCH',body:{display_name:name.trim()}});setProfile(d.data.user);await refreshProfile();setToast('Platform profile updated')}catch(e){setErr(e)}finally{setBusy('')}};
 const changePassword=async e=>{e.preventDefault();setErr(null);if(pw.new_password!==pw.confirm){setErr({code:'PASSWORD_MISMATCH',message:'New password and confirmation do not match'});return}setBusy('password');try{const d=await api.request('/v1/platform/me/change-password',{method:'POST',body:{current_password:pw.current_password,new_password:pw.new_password}});setPw({current_password:'',new_password:'',confirm:''});setToast(`Password changed · ${d.data.other_sessions_revoked||0} other session(s) revoked`);await load()}catch(e){setErr(e)}finally{setBusy('')}};
 const revoke=async id=>{setBusy(id);setErr(null);try{const d=await api.request(`/v1/platform/me/sessions/${encodeURIComponent(id)}`,{method:'DELETE'});if(d.data.current_session){location.hash='#/login';return}setToast('Session revoked');await load()}catch(e){setErr(e)}finally{setBusy('')}};
 const revokeOthers=async()=>{setBusy('others');setErr(null);try{const d=await api.request('/v1/platform/me/sessions/revoke-others',{method:'POST',body:{}});setToast(`${d.data.sessions_revoked||0} other session(s) revoked`);await load()}catch(e){setErr(e)}finally{setBusy('')}};
 return <><PageHeader title="My profile & security" description="Manage your Luke Shop platform identity, password and active control-plane sessions."/><ErrorBox error={err}/>{loading?<Loading/>:<div className="profile-control-grid">
  <Card title="Platform identity" subtitle="This profile is separate from merchant tenant accounts."><form className="form-stack" onSubmit={saveProfile}><Field label="Display name"><input required maxLength="120" value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Email"><input readOnly value={profile?.email||''}/></Field><div className="profile-meta-row"><div><span>Role</span><Badge tone="neutral">{profile?.role||'—'}</Badge></div><div><span>Status</span><Badge tone={tone(profile?.status)}>{profile?.status||'—'}</Badge></div><div><span>Password changed</span><strong>{when(profile?.password_changed_at)}</strong></div></div><div className="right"><button className="primary" disabled={busy==='profile'||!name.trim()}>{busy==='profile'?'Saving…':'Save profile'}</button></div></form></Card>
  <Card title="Change password" subtitle="Changing your password revokes every other active platform session."><form className="form-stack" onSubmit={changePassword}><Field label="Current password"><input required minLength="12" maxLength="128" type="password" value={pw.current_password} onChange={e=>setPw({...pw,current_password:e.target.value})}/></Field><Field label="New password" hint="At least 12 characters and must satisfy the backend password policy."><input required minLength="12" maxLength="128" type="password" value={pw.new_password} onChange={e=>setPw({...pw,new_password:e.target.value})}/></Field><Field label="Confirm new password"><input required minLength="12" maxLength="128" type="password" value={pw.confirm} onChange={e=>setPw({...pw,confirm:e.target.value})}/></Field><div className="right"><button className="primary" disabled={busy==='password'}>{busy==='password'?'Changing…':'Change password'}</button></div></form></Card>
  <Card title="Active sessions" subtitle="Review where your platform account is signed in and revoke sessions you do not recognize." className="profile-sessions-card"><div className="profile-session-head"><span>{sessions.length} active session(s)</span><button className="secondary" disabled={busy==='others'||sessions.filter(s=>!s.current).length===0} onClick={revokeOthers}>{busy==='others'?'Revoking…':'Revoke other sessions'}</button></div>{sessions.length?<div className="profile-session-list">{sessions.map(s=><div className="profile-session-row" key={s.id}><div><strong>{s.current?'Current session':'Platform session'}</strong><span>{s.user_agent||'Unknown browser/device'}</span><small>{s.request_ip||'IP unavailable'} · Last seen {when(s.last_seen_at)} · Expires {when(s.expires_at)}</small></div>{s.current?<Badge tone="success">CURRENT</Badge>:<button className="danger" disabled={busy===s.id} onClick={()=>revoke(s.id)}>{busy===s.id?'Revoking…':'Revoke'}</button>}</div>)}</div>:<p className="muted">No active sessions found.</p>}</Card>
 </div>}<Toast message={toast} onDone={()=>setToast('')}/></>;
}
