import React,{useEffect,useState}from'react';
import{useAuth}from'../auth/AuthContext.jsx';
import{Badge,Card,ErrorBox,Field,Loading,PageHeader,Toast,tone}from'../components/UI.jsx';

const defaults={storefront_localization:true,address_field_policy:true,pwa:true,tenant_pwa_branding:true};
export function TenantExperiencePage(){
 const{api,isOwner}=useAuth();const[tenants,setTenants]=useState([]),[ref,setRef]=useState(''),[detail,setDetail]=useState(null),[caps,setCaps]=useState(defaults),[limit,setLimit]=useState(4),[err,setErr]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>{api.request('/v1/platform/tenants').then(r=>setTenants(r.data.tenants||[])).catch(setErr)},[]);
 useEffect(()=>{if(!ref){setDetail(null);return}let live=true;setErr(null);api.request(`/v1/platform/tenants/${encodeURIComponent(ref)}`).then(r=>{if(!live)return;const t=r.data.tenant;setDetail(t);const overrides=t.platform?.overrides?.capabilities||{};const effective=t.platform?.capabilities||{};setCaps({...defaults,...effective,...overrides});const limits={...(t.platform?.limits||{}),...(t.platform?.overrides?.limits||{})};setLimit(Math.max(1,Math.min(4,Number(limits.storefront_languages||limits.customer_languages||4))))}).catch(e=>live&&setErr(e));return()=>{live=false}},[ref]);
 const save=async()=>{if(!detail||!isOwner)return;setBusy(true);setErr(null);try{const existingCaps=detail.platform?.overrides?.capabilities||{},existingLimits=detail.platform?.overrides?.limits||{};await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}`,{method:'PATCH',body:{capabilities:{...existingCaps,storefront_localization:Boolean(caps.storefront_localization),address_field_policy:Boolean(caps.address_field_policy),pwa:Boolean(caps.pwa),tenant_pwa_branding:Boolean(caps.tenant_pwa_branding)},limits:{...existingLimits,storefront_languages:Math.max(1,Math.min(4,Number(limit||4)))}}});setToast('Tenant experience capabilities updated');const r=await api.request(`/v1/platform/tenants/${encodeURIComponent(detail.id)}`);setDetail(r.data.tenant);}catch(e){setErr(e)}finally{setBusy(false)}};
 return <>
  <PageHeader title="Tenant experience capabilities" description="Control which storefront experience tools each client may use. Merchant Admin owns the actual tenant configuration." actions={detail&&isOwner&&<button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save capabilities'}</button>}/>
  <ErrorBox error={err}/>
  <Card title="Select client" subtitle="Capability overrides are tenant scoped and merge with the assigned plan."><Field label="Client platform"><select value={ref} onChange={e=>setRef(e.target.value)}><option value="">Choose tenant…</option>{tenants.map(t=><option key={t.id} value={t.id}>{t.name} · {t.slug}</option>)}</select></Field></Card>
  {ref&&!detail&&<Loading/>}
  {detail&&<div className="capability-grid">
   <Card title="Customer localization" subtitle="Allows Merchant Admin to enable customer storefront languages and manual content translations."><Capability checked={caps.storefront_localization!==false} disabled={!isOwner} onChange={v=>setCaps({...caps,storefront_localization:v})} label="Storefront localization"/><Field label="Maximum storefront languages" hint="Hard capped at four by Luke Customer Web."><input type="number" min="1" max="4" disabled={!isOwner||caps.storefront_localization===false} value={limit} onChange={e=>setLimit(e.target.value)}/></Field></Card>
   <Card title="Delivery address policy" subtitle="Allows the merchant to include or hide Label, Country code, Address line 2 and Postal code."><Capability checked={caps.address_field_policy!==false} disabled={!isOwner} onChange={v=>setCaps({...caps,address_field_policy:v})} label="Address field customization"/><p className="muted">When disabled, Backend enforces the safe default address form instead of tenant overrides.</p></Card>
   <Card title="Progressive Web App" subtitle="Foundation capability for installable Customer Web. Tenant branding controls are used by the next PWA branding release."><Capability checked={caps.pwa!==false} disabled={!isOwner} onChange={v=>setCaps({...caps,pwa:v})} label="PWA capability"/><Capability checked={caps.tenant_pwa_branding!==false} disabled={!isOwner||caps.pwa===false} onChange={v=>setCaps({...caps,tenant_pwa_branding:v})} label="Tenant PWA branding"/></Card>
   <Card title="Effective tenant" subtitle="Current platform context"><div className="detail-top"><div><span>Tenant</span><strong>{detail.name}</strong></div><div><span>Slug</span><strong>{detail.slug}</strong></div><div><span>Plan</span><strong>{detail.platform?.plan_key||'—'}</strong></div><div><span>Status</span><Badge tone={tone(detail.status)}>{detail.status}</Badge></div></div><p className="muted">Capabilities are platform governance only. Customer-facing settings remain under the tenant's Merchant Admin.</p></Card>
  </div>}
  <Toast message={toast} onDone={()=>setToast('')}/>
 </>;
}
function Capability({checked,onChange,label,disabled}){return <label className="capability-row"><span><strong>{label}</strong><small>{checked?'Allowed':'Not allowed'}</small></span><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>}
